backend:
  name: git-gateway
  repo: master

media_folder: "static/uploads"
public_folder: uploads

collections:
- name: "pages"
  label: "Pages"
  files:
    - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}