backend:
  name: github
  branch: master
  repo: fmeyer1980/indexed

media_folder: "static/uploads"
public_folder: uploads

collections:
- label: "Landing Pages"
  name: "landingpages"
  delete: false
  editor:
    preview: true
  files:
    - label: "Forside"
      name: "index"
      file: "src/pages/index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Path, name: path, widget: widget: "hidden", default: "/"}
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page-index"}
        - {label: Hero, name: hero, widget: object, fields: [{label: Heading 1, name: heading_1, widget: string}, {label: Heading 2, name: heading_2, widget: string}, {label: Text, name: text, widget: string}, {label: Image, name: image, widget: image}]}
        - {lable: Logos, name: logos, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Image, name: image, widget: image}, {label: Image, name: image, widget: image}, {label: Image, name: image, widget: image}]}
        - {label: Skills, name: skills, widget: object, fields: [ 
          {label: Skill, name: skill, widget: list, fields: [
            {label: Image, name: image, widget: image},
            {label: Icon, name: icon, widget: image},
            {label: Heading, name: heading, widget: string},
            {label: Text, name: text, widget: string},
            {label: Direction, name: direction, widget: string},
            {label: Bgcolor, name: bgcolor, widget: string}
            ]}
            ]}
    # - file: "src/pages/about/index.md"
    #   label: "About"
    #   name: "about"
    #   fields:
    #     - {label: Title, name: title, widget: string}
    #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default"}
    #     - {label: "Body", name: "body", widget: "markdown"}
    # - label: "Ydelser"
    #   name: "ydelser"
    #   file: "src/pages/ydelser/index.md"
    #   fields:
    #     - {label: Title, name: title, widget: string}
    #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default"}
    #     - {label: "Body", name: "body", widget: "markdown"}
- label: "Ydelser Undersider"
  name: "ydelserundersider"
  folder: "src/pages/ydelser"
  create: true
  slug: "{{slug}}"
  fields:
    - {label: Title, name: title, widget: string}
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default"}
    - {label: "Body", name: "body", widget: "markdown"}