backend:
  name: git-gateway
  repo: master

media_folder: "static/uploads"
public_folder: uploads

collections:
- label: "Landing Pages"
  name: "landingpages"
  delete: false
  editor:
    preview: true
  files:
    - label: "Forside"
      name: "index"
      file: "src/pages/index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "PageIndex"}
        - {label: "Body", name: "body", widget: "markdown"}
        - {label: Hero, name: hero, widget: object, fields: [
          {label: Heading 1, name: heading_1, widget: string},
          {label: Heading 2, name: heading_2, widget: string},
          {label: Text, name: text, widget: string}
          ]}
    - file: "src/pages/about/index.md"
      label: "About"
      name: "about"
      fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "PageIndex"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
    - label: "Ydelser"
      name: "ydelser"
      file: "src/pages/ydelser/index.md"
      fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "PageIndex"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
- label: "Ydelser Undersider"
  name: "ydelserundersider"
  folder: "src/pages/ydelser"
  create: true
  slug: "{{slug}}"
  fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "Post"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Description", name: "description", widget: "text"}
    - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
    - {label: "Featured Image", name: "featuredimage", widget: image}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Tags", name: "tags", widget: "list"}