backend:
  name: git-gateway
  repo: master

media_folder: "static/uploads"
public_folder: uploads

collections:
- label: "Pages"
  name: "pages"
  files:
    - label: "About"
      name: "about"
      file: "src/pages/about/index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "PageIndex"}
        - {label: "Body", name: "body", widget: "markdown"}